version: '2'
services:
  web:
    environment:
      - SEARCH_ENGINE=anserini
      - SEARCH_SERVER_IP=http://search
      - SEARCH_SERVER_PORT=80
      - INDEX_NAME=athome4

  search:
    build: ./search/
    environment:
      - ANSERINI_INDEXI_PATH=/data/lucene-index.athome.pos+docvectors+raw+content/
    volumes:
      - ./search/app:/app
      - ./data:/data
    ports:
      - "8003:80"
    expose:
      - "8003"

